In [418]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [419]:
pip install keras

In [420]:
import tensorflow as tf

In [421]:
from keras.preprocessing.image import ImageDataGenerator

In [422]:
tf.__version__

'2.7.0'

In [423]:
#pip install zipfile

In [424]:
import zipfile as zf

In [425]:
files =zf.ZipFile("Training-Set-Land.zip",'r')

In [426]:
files.extractall('Training-Set-Land')

In [427]:
files.close()

In [428]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)
training_set = train_datagen.flow_from_directory('Training-Set-Land/Training Set - Barren and Crop/',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'binary')

Found 310 images belonging to 2 classes.


In [429]:
file = zf.ZipFile("Test-Final.zip",'r')

In [430]:
file.extractall('Test-Final')

In [431]:
file.close()

In [432]:
test_datagen = ImageDataGenerator(rescale = 1./255)
test_set = test_datagen.flow_from_directory('Test-Final/TestFinal',
                                            target_size = (64, 64),
                                            batch_size = 32,
                                            class_mode = 'binary')

Found 0 images belonging to 0 classes.


In [433]:
cnn=tf.keras.models.Sequential()
cnn.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,activation='relu',input_shape=[64,64,3]))
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))
cnn.add(tf.keras.layers.Flatten())
cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))
cnn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
cnn.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
cnn.fit(x = training_set, validation_data = test_set, epochs = 11)


Epoch 1/11
10/10 [==============================] - 7s 472ms/step - loss: 0.3164 - accuracy: 0.9065
Epoch 2/11
10/10 [==============================] - 3s 315ms/step - loss: 0.1205 - accuracy: 0.9548
Epoch 3/11
10/10 [==============================] - 3s 309ms/step - loss: 0.0760 - accuracy: 0.9806
Epoch 4/11
10/10 [==============================] - 3s 336ms/step - loss: 0.0522 - accuracy: 0.9774
Epoch 5/11
10/10 [==============================] - 3s 314ms/step - loss: 0.0547 - accuracy: 0.9806
Epoch 6/11
10/10 [==============================] - 3s 309ms/step - loss: 0.0613 - accuracy: 0.9710
Epoch 7/11
10/10 [==============================] - 3s 307ms/step - loss: 0.0520 - accuracy: 0.9839
Epoch 8/11
10/10 [==============================] - 3s 319ms/step - loss: 0.0395 - accuracy: 0.9871
Epoch 9/11
10/10 [==============================] - 3s 319ms/step - loss: 0.0365 - accuracy: 0.9871
Epoch 10/11
10/10 [==============================] - 3s 311ms/step - loss: 0.0755 - accuracy: 0.9742

In [434]:
import numpy as np
from keras.preprocessing import image
s='Test-Final/TestFinal/'
array=[]
for i in range(20):
    s=s+'imagee'+str(i+1)+'.jpg'
    test_image = image.load_img(s, target_size = (64, 64))
    test_image = image.img_to_array(test_image)
    test_image = np.expand_dims(test_image, axis = 0)
    result = cnn.predict(test_image)
    training_set.class_indices
    if result[0][0] == 1:
      prediction = 'crop'
      array.append(1)
    else:
      prediction = 'barren'
      array.append(0)
    print(prediction)
    s='Test-Final/TestFinal/'
    

barren
barren
barren
barren
barren
barren
barren
barren
barren
barren
barren
barren
crop
barren
barren
crop


FileNotFoundError: [Errno 2] No such file or directory: 'Test-Final/TestFinal/imagee17.jpg'

In [435]:
array

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]

In [436]:
import zipfile as zf
file = zf.ZipFile("Training-Set-Water.zip",'r')
file.extractall("Training-Set-Water")
file.close()

In [437]:
train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)
training_set = train_datagen.flow_from_directory('Training-Set-Water/Training Set/',
                                                 target_size = (64, 64),
                                                 batch_size = 32,
                                                 class_mode = 'binary')

Found 720 images belonging to 2 classes.


In [438]:
cnn=tf.keras.models.Sequential()
cnn.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,activation='relu',input_shape=[64,64,3]))
cnn.add(tf.keras.layers.Conv2D(filters=32, kernel_size=3, activation='relu'))
cnn.add(tf.keras.layers.MaxPool2D(pool_size=2, strides=2))
cnn.add(tf.keras.layers.Flatten())
cnn.add(tf.keras.layers.Dense(units=128, activation='relu'))
cnn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
cnn.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
cnn.fit(x = training_set, validation_data = test_set, epochs = 15)


Epoch 1/15
23/23 [==============================] - 11s 453ms/step - loss: 0.7791 - accuracy: 0.5278
Epoch 2/15
23/23 [==============================] - 8s 331ms/step - loss: 0.6722 - accuracy: 0.6153
Epoch 3/15
23/23 [==============================] - 8s 324ms/step - loss: 0.6620 - accuracy: 0.6222
Epoch 4/15
23/23 [==============================] - 8s 328ms/step - loss: 0.6727 - accuracy: 0.6181
Epoch 5/15
23/23 [==============================] - 8s 324ms/step - loss: 0.6600 - accuracy: 0.6333
Epoch 6/15
23/23 [==============================] - 8s 329ms/step - loss: 0.6537 - accuracy: 0.6069
Epoch 7/15
23/23 [==============================] - 8s 328ms/step - loss: 0.6760 - accuracy: 0.5944
Epoch 8/15
23/23 [==============================] - 8s 329ms/step - loss: 0.6552 - accuracy: 0.6194
Epoch 9/15
23/23 [==============================] - 8s 324ms/step - loss: 0.6457 - accuracy: 0.6361
Epoch 10/15
23/23 [==============================] - 8s 327ms/step - loss: 0.6320 - accuracy: 0.644

In [439]:
import numpy as np
from keras.preprocessing import image
s='Test-Final/TestFinal/'
array1=[]
for i in range(20):
    s=s+'imagee'+str(i+1)+'.jpg'
    test_image = image.load_img(s, target_size = (64, 64))
    test_image = image.img_to_array(test_image)
    test_image = np.expand_dims(test_image, axis = 0)
    result = cnn.predict(test_image)
    training_set.class_indices
    if result[0][0] == 1:
      prediction = 'water'
      array1.append(1)
    else:
      prediction = 'dry'
      array1.append(0)
    print(prediction)
    s='Test-Final/TestFinal/'
    

dry
dry
dry
dry
dry
dry
dry
dry
dry
dry
dry
dry
dry
dry
dry
dry


FileNotFoundError: [Errno 2] No such file or directory: 'Test-Final/TestFinal/imagee17.jpg'

In [440]:
import pandas as pd
import numpy as np

In [441]:
df=pd.read_csv('Sample2.csv')

In [442]:
lat=df["Latitude"]
lat=np.array(lat)
lat

array([22.71, 22.34, 21.67, 24.55, 23.86, 23.11, 25.59, 25.22, 23.86,
       23.49, 23.11, 22.42, 22.05, 21.67, 24.55, 23.49, 24.15, 23.78,
       23.11, 22.05])

In [443]:
long=df["Longitude"]
long=np.array(long)
long

array([78.55, 80.36, 79.25, 81.48, 80.36, 81.13, 77.67, 79.52, 77.26,
       79.08, 78.04, 76.93, 78.73, 77.7 , 75.29, 75.99, 74.24, 76.06,
       74.95, 75.64])

In [444]:
import folium

In [445]:
mark_map = folium.Map(Location=[22.1,77.1],tiles = 'Stamen Terrain',zoom_start=6)

In [446]:
for i in range(16):
    if array[i]==0 and array1[i]==0:
        folium.Marker([lat[i],long[i]],popup = 'NWB',icon= folium.Icon(color='red')).add_to(mark_map)
    if array[i]==0 and array1[i]==1:
        folium.Marker([lat[i],long[i]],popup = 'WB',icon= folium.Icon(color='blue')).add_to(mark_map)
    if array[i]==1 and array1[i]==0:
        folium.Marker([lat[i],long[i]],popup = 'NWC',icon= folium.Icon(color='green')).add_to(mark_map)
    if array[i]==1 and array1[i]==1:
        folium.Marker([lat[i],long[i]],popup = 'WC',icon= folium.Icon(color='purple')).add_to(mark_map)

In [447]:
mark_map

In [448]:
array

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1]

In [449]:
array1

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [454]:
cloud=df["Clod Coverage"]
c=np.array(cloud)
c

array([-0.01,  0.67, -0.3 , -0.51,  0.31,  0.5 ,  0.09,  0.12, -0.09,
       -0.06, -0.08,  0.13, -0.13,  0.47, -0.03, -0.09,  0.  , -0.51,
       -0.5 , -0.36])

In [453]:
import folium
mark_map1 = folium.Map(Location=[22.1,77.1],tiles = 'Stamen Terrain',zoom_start=6)

In [456]:
for i in range(16):
    if c[i]<0:
        if c[i]<-0.5:
            folium.CircleMarker([lat[i],long[i]],radius = 15,popup = 'SD',color='red').add_to(mark_map1)
        else :
            folium.CircleMarker([lat[i],long[i]],radius = 15,popup = 'D',color='blue').add_to(mark_map1)
    else :
        if c[i]>0.5:
            folium.CircleMarker([lat[i],long[i]],radius = 15,popup = 'SD',color='green').add_to(mark_map1)
        else :
            folium.CircleMarker([lat[i],long[i]],radius = 15,popup = 'SD',color='yellow').add_to(mark_map1)

In [458]:
mark_map1